name = "carte"
defaultTargets = ["Carte"]

[[require]]
name = "iris"
path = "../Iris"

[[require]]
name = "Coinductive"
scope = "ISTA-PLV"
rev = "2d17379a8ba89d4e7892d70ac75ed7aab1090caa"

[[lean_lib]]
name = "Carte"
