name = "carte"
defaultTargets = ["Carte"]

[[require]]
name = "iris"
path = "../Iris"

[[require]]
name = "Coinductive"
scope = "ISTA-PLV"
rev = "1b88cd53fecf491831656b23bb5421d3448910ba"

[[lean_lib]]
name = "Carte"
