module

public import Iris.ProofMode.Expr
public import Iris.ProofMode.Aesop.Rule.Types.Match
public import Iris.ProofMode.Aesop.Tree.Types
public import Iris.ProofMode.Aesop.Util.Basic
public meta import Iris.ProofMode.Aesop.Search.Bubble.Types
public meta section

namespace Iris.ProofMode.Aesop

open Lean Lean.Meta Std
open Iris.ProofMode.Aesop

structure GoalData (RappRef ObunRef : Type) : Type where
  id : GoalId
  mask : ProgressMask
  parent : ObunRef
  children : Array RappRef
  origin : GoalOrigin

  depth : Nat
  state : GoalState
  isIrrelevant : Bool

  -- Turn true because of reaching the search depth limit
  isForcedUnprovable : Bool
  preNormGoal : MVarId
  preNormState : SavedState
  normalizationState : NormalizationState

  unassignedMvars : Std.HashSet MVarId
  successProbability : Percent
  addedInIteration : Iteration
  lastExpandedInIteration : Iteration

  rulesQueue : RuleQueue
  appendiedGoalId : Array GoalId

  /- ### Context manage data -/
  /- Split case identifier for this goal; `0` means it is not tied to a split case. -/
  caseId? : Option CaseId

  deriving Nonempty

structure ObunData (GoalRef RappRef : Type) : Type where
  /- ### Shared tree data (Copy and Bubble) -/
  id : ObunId
  parent? : Option RappRef
  goals : Array GoalRef

  state : NodeState
  isIrrelevant : Bool

  /- ### Shared context-management data (Copy and Bubble) -/
  /- Indicates whether this obligation bundle uses context-management mode. -/
  kind : ObunKind
  /- Nesting depth of active context-management frames. -/
  contextDepth : Nat
  /- Full-context Iris subgoal templates managed by this obligation bundle. -/
  fullContextIrisSubgoals : Array IrisGoal

  /- ### Copy-only data -/
  /- Finalized spatial-context split assignments, ordered by split case. -/
  finalizedSpatialSplits : Array (Array IrisHyp)

  /- ### Bubble-only data -/
  /- Original committed-goal indices, partitioned into connected components
  through shared unassigned metavariables.  Each component is one outer
  platform slot. -/
  bubbleDependencyRoots : Array (Array Nat) := #[]
  /- All initial and residual groups owned by this Obun.  Residual alternatives
  are appended here and retain their `preGroup?` link. -/
  bubbleGroups : Array (Search.Bubble.GoalGroupData GoalRef) := #[]
  /- The Obun-level incremental join.  A completed group is registered in the
  slot identified by its `rootIndex`. -/
  bubblePlatform? : Option (Search.Bubble.Platform IrisHyp) := none

  /- ### Shared script-generation data (Copy and Bubble) -/
  scriptSteps? : Option (Array Script.LazyStep)

  deriving Nonempty

structure RappData (GoalRef ObunRef : Type) : Type where
  id : RappId
  parent : GoalRef
  children : ObunRef

  state : NodeState
  isIrrelevant : Bool

  appliedRule : Rule RuleInfo
  successProbability : Percent

  /- ### Script generation data -/
  scriptSteps? : Option (Array Script.LazyStep)

  /- Concrete hypotheses used (consumed) by this rule application.
     Most rules use at most one, but context-transforming rules (e.g. `imodintro`'s `inext`,
     which rewrites `▷X` to `X`) may consume several spatial hypotheses at once. -/
  usedHyps : Array AppliedHyp
  /- Concrete spatial hypotheses generated by this rule application. -/
  generatedSpatialHyps : Array IrisHyp

  /- ### Lean context-related data -/
  /- Meta state immediately after the rule application succeeds. -/
  metaState : SavedState
  /- Expression metavariables introduced by this rule application. -/
  introducedMVars : Std.HashSet MVarId
  /- Existing expression metavariables assigned by this rule application. -/
  assignedMVars : Std.HashSet MVarId

  deriving Nonempty

end Aesop
