name = "irisitree"
defaultTargets = ["IrisITree"]

[[require]]
name = "iris"
path = "../Iris"

[[require]]
name = "Coinductive"
scope = "ISTA-PLV"
rev = "6f6e94cbacc7e5f698e4426e75cd8fa8a0e382bd"

[[lean_lib]]
name = "IrisITree"
