name = "irisitree"
defaultTargets = ["IrisITree"]

[[require]]
name = "iris"
path = "../Iris"

[[require]]
name = "Coinductive"
scope = "ISTA-PLV"
rev = "00f8e8213b8b147219377611679e149187c1c42f"

[[lean_lib]]
name = "IrisITree"
