module

public meta import Iris.ProofMode.Aesop.Search.Bubble.BubbleM
public meta import Iris.ProofMode.Aesop.Search.Bubble.Meta
public meta import Iris.ProofMode.Aesop.Search.Bubble.Group
public meta import Iris.ProofMode.Aesop.Search.Shared.Names

public meta section

namespace Iris.ProofMode.Aesop.Search.Bubble

open Lean Meta
open Iris.ProofMode
open Iris.ProofMode.Aesop

variable {Q : Type} [Queue Q]

private def sameResource (a b : IrisHyp) : Bool :=
  a.ivar == b.ivar

private def normalizeFootprint (hyps : Array IrisHyp) : Array IrisHyp :=
  hyps.foldl (init := #[]) fun acc hyp =>
    if acc.any (sameResource hyp) then acc else acc.push hyp

private def formatFootprint (hyps : Array IrisHyp) : String :=
  "[" ++ String.intercalate ", " (hyps.toList.map toString) ++ "]"

/- Lift a child footprint through one proof step.  Resources generated by the
step are local and disappear from the footprint; resources consumed by the
step are added. -/
private def liftFootprint (inner generated consumed : Array IrisHyp) : Array IrisHyp :=
  normalizeFootprint <|
    (inner.filter fun used => !generated.any (sameResource used)) ++ consumed

private def goalFootprint (goal : Goal) (inner : Array IrisHyp) : Array IrisHyp :=
  liftFootprint inner goal.normalizationState.generatedSpatialHyps
    goal.normalizationState.usedSpatialHyps

/- A bubble reported for `goal` may only consume resources that existed in
that goal's incoming context.  This removes branch-local hypotheses generated
by rules such as `icases`, including resources whose generated identity differs
between duplicated branches. -/
private def retainIncomingResources (goal : Goal) (consumed : Array IrisHyp) :
    BubbleM Q (Array IrisHyp) := do
  let incoming ← liftM (m := Iris.ProofMode.Aesop.CoreM Q) <|
    liftM (m := MetaM) do
      let current ← saveState
      goal.preNormState.restore
      let resources ← goal.preNormGoal.withContext do
        let type ← instantiateMVars (← goal.preNormGoal.getType)
        let some irisGoal := parseIrisGoal? type
          | throwError "iaesop(bubble): expected an Iris goal while computing footprint"
        return (spatialHypEntries irisGoal.hyps).map fun (name, ivar, _) => { name, ivar }
      current.restore
      return resources
  return consumed.filter fun used => incoming.any (sameResource used)

mutual

partial def deliverBubble (bubble : ProofBubble) : BubbleM Q Unit := do
  let goal ← bubble.goal.get
  let obun ← goal.parent.get
  if obun.parent?.isNone then
    setRootSolution bubble.id
    return
  let emissions ← arriveGoalBubble bubble
  trace[iaesop.search.bubble] "iaesop(bubble): deliver bubble {bubble.id} from goal \
    {goal.id} to group coordinator; emissions={emissions.size}"
  for emission in emissions do
    emitRappBubble emission.rapp emission.children emission.consumed

partial def emitRappBubble (rappRef : RappRef) (children : Array BubbleId)
    (childrenConsumed : Array IrisHyp) : BubbleM Q Unit := do
  let rapp ← rappRef.get
  let parentGoal ← rapp.parent.get
  let childBubbles ← children.mapM getBubble
  /- Most resource-allocation bubbles do not mention expression metavariables.
  Keep their hot path purely structural instead of restoring a meta state for
  an assignment delta that must be empty. -/
  let rappMetaInfo ←
    if parentGoal.unassignedMvars.isEmpty then pure #[]
    else collectIncomingMetaInfo parentGoal rapp.metaState
  let some metaInfo ← mergeMetaInfo rapp.metaState <|
      #[rappMetaInfo] ++ childBubbles.map (fun bubble => bubble.metaInfo)
    | trace[iaesop.search.bubble] "iaesop(bubble): reject incompatible metavariable \
        combination at goal {parentGoal.id}"
      return
  let consumed :=
    liftFootprint childrenConsumed rapp.generatedSpatialHyps rapp.consumedSpatialHyps
    |> goalFootprint parentGoal
  /- Managed and plain proof steps already report generated resources exactly.
  Duplicated branches (notably `icases`) can generate a different resource ID
  per branch, so only they need the expensive incoming-context projection. -/
  let childObun ← rapp.children.get
  let consumed ←
    if childObun.kind.isDuplicated then retainIncomingResources parentGoal consumed
    else pure consumed
  let pre ← goalPre? parentGoal.id
  let bubble ← registerBubble rapp.parent consumed metaInfo (.rule rappRef children) pre
  trace[iaesop.search.bubble] "iaesop(bubble): bubble {bubble.id} solves goal \
    {parentGoal.id} via {rapp.appliedRule.info.builder}; children={children.size}; \
    consumed={formatFootprint consumed}; meta={metaInfo.size}"
  deliverBubble bubble

end

def emitNormalizationBubble (goalRef : GoalRef) : BubbleM Q Unit := do
  let goal ← goalRef.get
  let consumed := normalizeFootprint goal.normalizationState.usedSpatialHyps
  let postState := match goal.normalizationState with
    | .provenByNorm postState .. => postState
    | .normal _ postState .. => postState
    | .notNormal => goal.preNormState
  let metaInfo ←
    if goal.unassignedMvars.isEmpty then pure #[]
    else collectIncomingMetaInfo goal postState
  let pre ← goalPre? goal.id
  let bubble ← registerBubble goalRef consumed metaInfo .normalization pre
  trace[iaesop.search.bubble]
    "iaesop(bubble): normalization bubble {bubble.id} solves goal {goal.id}"
  deliverBubble bubble

end Iris.ProofMode.Aesop.Search.Bubble
